import React, { useEffect, useState } from 'react'
import Head from 'next/head'

import { Col, Container, Row, Tab, Tabs  } from 'react-bootstrap'

import GameSelector from '../components/GameSelector'
import GameHeader from '../components/GameHeader'
import PeriodHeader from '../components/RecapSelector'
import DisplayRecap from '../components/DisplayRecap'

import BIFVsLHC from '../public/data/12771.json'
import BIFVsFBK from '../public/data/12915.json'
import FHCVsIKO from '../public/data/12939.json'

const Home = () => {
  const [gameId, setGameId] = useState('12771')
  const [teamLogo, setTeamLogo] = useState({})
  const [recap, setRecap] = useState({})
  const [recapPeriod, setRecapPeriod] = useState('gameRecap')

  useEffect(() => {
    fetch(`./data/${gameId}.json`)
      .then((res) => res.json())
      .then((data) => {
        categorizeData(data)
      })
  }, [])

  const categorizeData = (data) => {
    setRecap(data?.recaps)

    const homeTeamLogo= data?.recaps?.gameRecap?.homeTeamId
    const awayTeamLogo = data?.recaps?.gameRecap?.awayTeamId

    const logos = {
      homeTeam: {
        abv: homeTeamLogo,
        name: data?.recaps?.gameRecap?.homeTeamName
      },
      awayTeam: {
        abv: awayTeamLogo,
        name: data?.recaps?.gameRecap?.awayTeamName
      }
    }

    setTeamLogo(logos)
  }

  const handleGameSelectorChange = (value) => {
    let data;
    switch(value) {
      case '12915':
        data = JSON.parse(JSON.stringify(BIFVsFBK))
        break
      case '12939':
        data = JSON.parse(JSON.stringify(FHCVsIKO))
        break
      case '12771':
      default:
        data = JSON.parse(JSON.stringify(BIFVsLHC))
        break
    }
    setGameId(value)
    categorizeData(data)
  }

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Row>
        <Col className='my-5 ' md={{ span: 6, offset: 3}} lg={{ span: 4, offset: 4}}>
          <GameSelector selectChange={handleGameSelectorChange} />
        </Col>
      </Row>
      <Row>
        <Col className='mb-5'>
          <GameHeader teamLogo={teamLogo} />
        </Col>
      </Row>
      <Row className='mb-5'>
        <Col>
          <Row>
            <Col className='mt-3 mb-5' md={{ span: 2, offset: 5}}>
              <PeriodHeader setChange={setRecapPeriod} periods={ Object.keys(recap) } />
            </Col>
          </Row>
          <Row>
            <Col>
              <DisplayRecap stats={ recap[recapPeriod] } />
            </Col>
          </Row>
        </Col>
      </Row>
    </Container>
  )
}

export default Home
